dronedream_agent_msgs/MissionSegment segment
---
bool accepted
string terminal_status
string evidence_sha256
dronedream_agent_msgs/MissionObservation final_observation
string[] issue_codes
---
dronedream_agent_msgs/MissionObservation observation
dronedream_agent_msgs/SafetyEvent safety
